services:

  rag-ai-service:
    build:
      context: ./rag-ai-service
    container_name: rag-ai-service
    restart: unless-stopped
    environment:
      EMBEDDING_PROVIDER: aliyun-bailian-openai-compatible
      EMBEDDING_BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
      EMBEDDING_API_KEY: ${DASHSCOPE_API_KEY:-}
      EMBEDDING_DEFAULT_MODEL: text-embedding-v4
      CHAT_PROVIDER: deepseek-openai-compatible
      CHAT_BASE_URL: https://api.deepseek.com
      CHAT_API_KEY: ${DEEPSEEK_API_KEY:-}
      CHAT_DEFAULT_MODEL: deepseek-v4-pro
      RERANK_PROVIDER: aliyun-bailian
      RERANK_BASE_URL: ${RERANK_BASE_URL:-https://dashscope.aliyuncs.com/api/v1}
      RERANK_API_KEY: ${DASHSCOPE_API_KEY:-}
      RERANK_DEFAULT_MODEL: qwen3-rerank
      RERANK_PATH: ${RERANK_PATH:-/services/rerank/text-rerank/text-rerank}
      RERANK_REQUEST_FORMAT: ${RERANK_REQUEST_FORMAT:-dashscope-input}
    ports:
      - "8001:8001"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    restart: always
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5432:5432"
    volumes:
      - ./rag-backend/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rag-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass rag_password
      --maxmemory 256mb
      --maxmemory-policy noeviction
    volumes:
      - ./rag-backend/data/redis:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: rag-redisinsight
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - ./rag-backend/data/redisinsight:/data

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: rag-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-rag_minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-rag_minio_password}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./rag-backend/data/minio:/data
