services:

  embedding-service:
    build:
      context: ./embedding-service
    container_name: rag-embedding-service
    restart: always
    ports:
      - "8001:8001"
    environment:
      EMBEDDING_MODEL_NAME: BAAI/bge-small-zh-v1.5
      EMBEDDING_MODEL_PATH: /models/bge-small-zh-v1.5
      EMBEDDING_DEVICE: cpu
      EMBEDDING_NORMALIZE: "true"
      EMBEDDING_LOCAL_FILES_ONLY: "true"
      EMBEDDING_PORT: 8001
    volumes:
      - ./data/huggingface:/root/.cache/huggingface
      - ./data/models:/models

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    restart: always
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rag-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass rag_password
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data
