logging:
  level:
    "[com.example.rag]": DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: rag_user
    password: rag_password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: rag_password
      timeout: 3s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
